name: Grab Artifact Containers Demo

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to get image'
        required: true
        type: string

jobs:
  demo-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Install Latest Docker Version
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      
      - name: Pull artifacts using GH CLI
        run: |
          mkdir $RUNNER_TEMP/images && cd $RUNNER_TEMP/images
          gh run download -n Anax-Images-v${{ inputs.version }}
          ls -la
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          GH_HOST: github.com
          
  demo-API:
    runs-on: ubuntu-latest

    steps:
      - name: Install Latest Docker Version
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      
      - name: Pull artifacts using GH Rest API
        run: |
          mkdir $RUNNER_TEMP/images && cd $RUNNER_TEMP/images

          export ARTIFACT_ID=$( \
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/blakep7/demo_release/actions/artifacts?per_page=100 \
              | jq -c '(.artifacts[] | select ( .name == "Anax-Images-v${{ inputs.version }}")).id')
          
          echo $ARTIFACT_ID

          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/blakep7/demo_release/actions/artifacts/${ARTIFACT_ID}/zip \
            -o Artifact_Holder.zip

          ls -la

          7z x Artifact_Holder.zip

          ls -la

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

