name: Demo Workflow

on: workflow_dispatch

jobs:
  demo-job:
    runs-on: ubuntu-latest
    # environment: demo-release-env
    steps:
      # Upgrade Docker engine version, needed for building images
      - name: Install Latest Docker Version
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      
      - name: Save Docker Image
        run: |
          mkdir $RUNNER_TEMP/test_images
          cd $RUNNER_TEMP/test_images
          docker pull blakep7/arm64_anax:testing
          docker pull blakep7/amd64_anax:testing
          docker save blakep7/arm64_anax:testing | gzip > arm64_anax.tar.gz      
          docker save blakep7/amd64_anax:testing | gzip > amd64_anax.tar.gz

      - name: Upload Container to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Anax-Images-v${{ github.run_number }}
          path: ${{ runner.temp }}/test_images/*