name: Demo Workflow

on: workflow_dispatch
//
jobs:
  demo-job:
    runs-on: ubuntu-latest
    # environment: demo-release-env
    steps:
      # Upgrade Docker engine version, needed for building images
      - name: Install Latest Docker Version
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      
      - name: Save Docker Image
        run: |
          mkdir $RUNNER_TEMP/test_images
          cd $RUNNER_TEMP/test_images

          images=('amd64_agbot' 'amd64_anax' 'amd64_anax_k8s' 'amd64_auto-upgrade-cronjob_k8s' 'amd64_cloud-sync-service' 'amd64_edge-sync-service' 'ppc64el_anax' 'ppc64el_anax_k8s' 'ppc64el_auto-upgrade-cronjob_k8s' 'ppc64el_edge-sync-service' 'arm64_anax' 'arm64_anax_k8s' 'arm64_auto-upgrade-cronjob_k8s' 'arm64_edge-sync-service')

          for image in "${images[@]}"; do \
            docker pull blakep7/${image}:testing; \
            docker save blakep7/${image}:testing | gzip > ${image}.tar.gz; \
          done

      # We add this to all workflows for all docker images that are published
      - name: Upload Container to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Anax-Images-v${{ github.run_number }}
          path: ${{ runner.temp }}/test_images/*