name: Test Workflow

on:
  push:
    paths:
      - '**'


jobs:
  demo-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Test
        run: |
          echo ${{ github.event_path }}

          
      