name: Test Workflow

on: workflow_dispatch

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          images=($ENVIMAGES)
          for image in "${images[@]}"; do
              echo $image
          done
        env:
          ENVIMAGES: "test1 test2 test3"

      